### ISSUE TITLE
Add Gitea

### ISSUE THREAD

**Issue by ch3p4ll3** [awesome-foss/awesome-sysadmin#564] opened 2024-03-26 14:53 UTC
Gitea is a painless self-hosted all-in-one software development service, including Git hosting, code review, team collaboration, package registry and CI/CD. It's open source under MIT license.

**Comment by nodiscc** [comment] 2024-03-26 16:51
duplicate of https://awesome-selfhosted.net/tags/software-development---project-management.html#gitea

**Closed by nodiscc** 2024-03-26 16:51 UTC
